export const contactDetails = {
	address: "Patna, Bihar",
	email: "contact.akashdeep023@gmail.com",
	phone: "+91 6207524516",
};

export const projectDetails = [
	{
		name: "Chat App",
		live: "https://chat-application-jack.vercel.app/",
		github: "https://github.com/akashdeep023/Chat_App",
		linkedin:
			"https://www.linkedin.com/posts/akashdeep023_chatapp-mernabrstack-mernstack-activity-7222507586980388864-XiV0?utm_source=share&utm_medium=member_desktop",
		image: "img",
		description: "Chat Application Using MERN Stack with Tailwind CSS",
		technoloty: [
			"React.js",
			"Redux",
			"Socket.IO",
			"Node.js",
			"MongoDB",
			"Express.js",
			"Tailwind-CSS",
			"JavaScript",
		],
		project: "Major Project",
	},
	{
		name: "Airbnb Project",
		live: "https://airbnb-project-major-jack.onrender.com/",
		github: "https://github.com/akashdeep023/Airbnb_Project",
		linkedin:
			"https://www.linkedin.com/posts/akashdeep023_airbnb-apnacollege-fullstackdevelopment-activity-7153710900992970752-Z9_G?utm_source=share&utm_medium=member_desktop",
		image: "img",
		description:
			"A feature-rich full-stack web application inspired by Airbnb.",
		technoloty: [
			"EJS",
			"Node.js",
			"MongoDB",
			"Express.js",
			"Bootstrap",
			"JavaScript",
			"Passport.js",
			"MapBox",
			"Cloudinary",
		],
		project: "Major Project",
	},
	{
		name: "Food Plaza",
		live: "https://food-plaza-project.vercel.app/",
		github: "https://github.com/akashdeep023/Food_Plaza",
		linkedin:
			"https://www.linkedin.com/posts/akashdeep023_foodplaza-namastedev-namastereact-activity-7168890857792761856-qC0D?utm_source=share&utm_medium=member_desktop",
		image: "img",
		description:
			"Welcome to Food Plaza, a cutting-edge food delivery app designed to revolutionize your dining experience. Get ready to enjoy seamless food ordering with a user-friendly interface and personalized features.",
		technoloty: ["React.js", "Redux", "CSS", "JavaScript"],
		project: "Major Project",
	},
	{
		name: "Netflix Gpt",
		live: "https://netflix-gpt-jack.vercel.app/",
		github: "https://github.com/akashdeep023/Netflix_Gpt",
		linkedin:
			"https://www.linkedin.com/posts/akashdeep023_netflixgpt-openai-gpt-activity-7172444217913360385-pPZ4?utm_source=share&utm_medium=member_desktop",
		image: "img",
		description:
			"Greetings, movie lovers! Welcome to Netflix-GPT, a state-o-the-art movie recommendation website powered by the GPT model and Firebase.",
		technoloty: [
			"React.js",
			"Redux",
			"Tailwind-CSS",
			"JavaScript",
			"FireBase",
		],
		project: "Major Project",
	},
	{
		name: "Cors Handler",
		live: "https://cors-handlers.vercel.app/",
		linkedin:
			"https://www.linkedin.com/posts/akashdeep023_webdevelopment-nodejs-expressjs-activity-7184854679493783553-dFXF?utm_source=share&utm_medium=member_desktop",
		image: "img",
		description: "--------------------------------",
		technoloty: [
			"EJS",
			"Node.js",
			"Express.js",
			"HTML",
			"CSS",
			"JavaScript",
		],
		project: "Major Project",
	},
	{
		name: "Code With",
		live: "https://code-with.vercel.app/",
		image: "img",
		description: "--------------------------------",
		technoloty: [
			"React.js",
			"Node.js",
			"MongoDB",
			"Express.js",
			"Tailwind-CSS",
			"JavaScript",
		],
		project: "Client Project",
	},
	{
		name: "Drioh Project",
		live: "https://drioh.vercel.app/",
		image: "img",
		description: "--------------------------------",
		technoloty: ["React.js", "Tailwind-CSS", "JavaScript"],
		project: "Client Project",
	},
	{
		name: "Quable Food",
		live: "https://quablefoods.vercel.app/",
		image: "img",
		description: "--------------------------------",
		technoloty: ["React.js", "Tailwind-CSS", "JavaScript"],
		project: "Client Project",
	},
	{
		name: "Life Track",
		live: "https://todo-mern-project.vercel.app/",
		github: "https://github.com/akashdeep023/Todo_Mern",
		image: "img",
		description: "--------------------------------",
		technoloty: [
			"React.js",
			"Node.js",
			"MongoDB",
			"Express.js",
			"Tailwind-CSS",
			"JavaScript",
		],
		project: "Mini Major Project",
	},
	{
		name: "Weather Widget",
		live: "https://weather-widget-react-jack.netlify.app/",
		github: "https://github.com/akashdeep023/Weather_Widget",
		image: "img",
		description: "This is a simple weather app.",
		technoloty: ["React.js", "Material-UI", "HTML", "CSS", "JavaScript"],
		project: "Mini Major Project",
	},
	{
		name: "SimonSay Game Js",
		live: "https://akashdeep023.github.io/SimonSay_Game/",
		github: "https://github.com/akashdeep023/SimonSay_Game",
		image: "img",
		description:
			"Simon Says is a classic memory game where players must remember and repeat a sequence of colors and sounds. This project is a web-based implementation of the Simon Says Game.",
		technoloty: ["HTML", "CSS", "JavaScript"],
		project: "Mini Major Project",
	},
	{
		name: "Amazon Clone",
		live: "https://akashdeep023.github.io/Amazon-Clone/",
		github: "https://github.com/akashdeep023/Amazon-Clone",
		image: "img",
		description:
			"A clone of the Spotify website for practicing web development skills.",
		technoloty: ["HTML", "CSS", "JavaScript"],
		project: "Mini Major Project",
	},
	{
		name: "Spotify Clone",
		live: "https://akashdeep023.github.io/Spotify-Clone/",
		github: "https://github.com/akashdeep023/Spotify-Clone",
		image: "img",
		description:
			"A clone of the Spotify website for practicing web development skills.",
		technoloty: ["HTML", "CSS"],
		project: "Mini Major Project",
	},
];
